[[redirects]]
  from = "/contactus"
  to = "/"
  status = 200
  force = false
  query = {path = ":path"} #  apply this rule for /old-path?path=example
  conditions = {Language = ["en","es"], Country = ["US"]}
